sudo: required
services:
    - docker

before_install:
    - docker build -t jasonosborne/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jasonosborne/docker-react npm test -- --coverage