version: '3'
services:
    web:
        build:
            # Where to look for files/folders.
            context: .
            # What is the dockerfile name?
            dockerfile: Dockerfile.dev

        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - .:/app

    tests:
        build:
            # Where to look for files/folders.
            context: .
            # What is the dockerfile name?
            dockerfile: Dockerfile.dev

        volumes:
            - /app/node_modules
            - .:/app
        command: ["npm", "test"]